name: QQQ Alert

on:
  schedule:
    - cron: '40 18 * * 1-5'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell Script
        shell: pwsh
        env:
          STOOQ_APIKEY: ${{ secrets.STOOQ_APIKEY }}
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

        run: ./alertQQQ.ps1
